### ISSUE TITLE
testscript.cs 파일의 한글이 깨지는 듯 합니다.

### ISSUE THREAD

**Issue by ruelveldic** [Pruehen/Project-FE#1]
이슈
- testscript.cs 파일의 한글이 깨지는 듯 합니다.

![image](https://github.com/user-attachments/assets/478d8494-72ba-452b-983b-225f54e0caa3)
요 옵션도 체크되어 있는 상태에요.

현상
- VS2019로 열었을 때 결과
![image](https://github.com/user-attachments/assets/76d8ce36-4d96-4d98-ae67-43f588371dc4)
![image](https://github.com/user-attachments/assets/78596d03-9a25-4fb6-8711-802f256d8bf1)

- 윈도우 메모장으로 열었을 때 결과
![image](https://github.com/user-attachments/assets/2372db26-fb90-4517-8ce7-4d839940c857)

- notepad++로 열었을 때 결과
아무 내용이 보이지 않습니다.(새 파일과 동일)

요청
- 텍스트 편집에 지장이 없도록 파일 포멧 혹은 제 세팅 검토 부탁 드려요

**Comment by Pruehen** [comment]
확인했습니다. 제 작업 환경에서는 해당 문제가 발생하지 않고 있습니다.

![image](https://github.com/user-attachments/assets/83de3331-d261-4e2f-9c7c-0bfe00b605a3)
![image](https://github.com/user-attachments/assets/a010c51e-00cf-4d35-a43a-7aef3c1916b7)

예상 원인

- 비주얼 스튜디오의 버전이 달라서일 가능성이 있습니다. Visual Studio Community 2022 를 사용하면 해결될 수 있습니다.

![image](https://github.com/user-attachments/assets/0a546fbf-485f-4ed5-b5c5-d5eef2b979c9)

- 현재 위 이미지대로의 워크로드 세팅을 사용중입니다.
- 만약 버전 변경이 어려우실 경우, 말씀해주시면 제가 버전을 변경해서 작업해보겠습니다 :)

**Comment by ruelveldic** [comment]
1. VS Express 2019 -> 2022 교체 후 재현
2. 윈도우 시스템 로캘 설정 변경으로 해결
[제어판] - [국가 또는 지역] - [관리자 옵션] - [시스템 로캘 변경]
Beta: 세계 언어 지원을 위해 Unicode UTF-8 사용 언체크
![image](https://github.com/user-attachments/assets/fe6c2077-1b82-4308-9bd5-b166318cc9e7)
